/*
 * Ntropy Transaction API
 *
 * The world's most powerful, multi-geo, multi-lingual transaction categorization API.
 *
 * The version of the OpenAPI document:
 * Contact: api@ntropy.com
 * Generated by: https://openapi-generator.tech
 */

/// AccountHolderMetricsQuery : Query object for fetching an account holder's metrics

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccountHolderMetricsQuery {
    #[serde(rename = "metrics", skip_serializing_if = "Option::is_none")]
    pub metrics: Option<Vec<crate::models::AccountHolderMetricName>>,
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<String>,
    #[serde(rename = "end", skip_serializing_if = "Option::is_none")]
    pub end: Option<String>,
}

impl AccountHolderMetricsQuery {
    /// Query object for fetching an account holder's metrics
    pub fn new() -> AccountHolderMetricsQuery {
        AccountHolderMetricsQuery {
            metrics: None,
            start: None,
            end: None,
        }
    }
}
