/*
 * Ntropy Transaction API
 *
 * The world's most powerful, multi-geo, multi-lingual transaction categorization API.
 *
 * The version of the OpenAPI document:
 * Contact: api@ntropy.com
 * Generated by: https://openapi-generator.tech
 */

/// AccountHolderMetricName : String specifying a metric name for query object

/// String specifying a metric name for query object
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountHolderMetricName {
    #[serde(rename = "overall_stats")]
    OverallStats,
    #[serde(rename = "stats_by_label")]
    StatsByLabel,
    #[serde(rename = "stats_by_merchant")]
    StatsByMerchant,
}

impl ToString for AccountHolderMetricName {
    fn to_string(&self) -> String {
        match self {
            Self::OverallStats => String::from("overall_stats"),
            Self::StatsByLabel => String::from("stats_by_label"),
            Self::StatsByMerchant => String::from("stats_by_merchant"),
        }
    }
}

impl Default for AccountHolderMetricName {
    fn default() -> AccountHolderMetricName {
        Self::OverallStats
    }
}
