/*
 * Ntropy Transaction API
 *
 * The world's most powerful, multi-geo, multi-lingual transaction categorization API.
 *
 * The version of the OpenAPI document:
 * Contact: api@ntropy.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransactionErrorErrorDetails {}

impl TransactionErrorErrorDetails {
    pub fn new() -> TransactionErrorErrorDetails {
        TransactionErrorErrorDetails {}
    }
}
