/*
 * Ntropy Transaction API
 *
 * The world's most powerful, multi-geo, multi-lingual transaction categorization API.
 *
 * The version of the OpenAPI document:
 * Contact: api@ntropy.com
 * Generated by: https://openapi-generator.tech
 */

/// TransactionError : Transaction that returned with error.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransactionError {
    #[serde(rename = "error")]
    pub error: String,
    #[serde(rename = "error_details", skip_serializing_if = "Option::is_none")]
    pub error_details: Option<serde_json::Value>,
}

impl TransactionError {
    /// Transaction that returned with error.
    pub fn new(error: String) -> TransactionError {
        TransactionError {
            error,
            error_details: None,
        }
    }
}
